# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

# To change the external link values for the below, do so in the pages directory, where their redirects live.
menu:
- {name: 'OLAT',  url: 'olat'}
- {name: 'Etherpad',  url: 'pad'}
- {name: 'Polls',  url: 'poll'}
- {name: 'Zotero',  url: 'zotero'}
- {name: 'Chat',  url: 'chat'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {fa-class: 'brands', icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {fa-class: 'brands', icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {fa-class: 'brands', icon: 'instagram', link:  'https://instagram.com/paululele'}
# - {fa-class: 'solid', icon: 'envelope', link:   'mailto:hello@paulle.ca'}
# - {fa-class: 'solid', icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

base-urls:
  pad: 'https://etherpad.studiumdigitale.uni-frankfurt.de/p/24inter'
  polls: 'https://ars.particify.de/p/55069903/series'
  zotero: 'https://www.zotero.org/groups/5490829/24inter'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
